### ISSUE TITLE
hover label bug

### ISSUE THREAD

**Issue by cmahony** [bcgov/CCISS_spatial#13]
the hover label sometime seems to be mislabelling, presumably due to colour variability from image compression. for example, the analog in the image below is CDFmm, but the label is IDFxx2 (which has a similar color to CDFmm). on click, the plot for IDFxx2 is shown. 

![Image](https://github.com/user-attachments/assets/8cd79eca-efa6-45e5-8ec2-e68fe8fc68af)

**Comment by kdaust** [comment]
Seems to be fixed with the higher res rasters
