### ISSUE TITLE
features for first version

### ISSUE THREAD

**Issue by cmahony** [bcgov/CCISS_spatial#3]
The goal with the first version is to support expert review. here are the features that i think will be required. 
- [ ] reference period (1961-1990) BGC and feasibility
- [x] BGC map layer (as underlay)
- [ ] blank map layer (i.e., as currently in the BGC map layer)
- [ ] "about" tab with documentation and how-to (rest of team can populate this). 
- [x] results for all species
- [x] ensemble vote BGC as default
- [x] stacked bar chart for popup, ideally with multiple periods
- [x] correct BGC colours for popup graphics. 
- [x] observed (2001-2020) period (if possible).

**Comment by kdaust** [comment]
Moved remaining to new version
